// <auto-generated />
using System;
using FitnessApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessApp.Data.Migrations
{
    [DbContext(typeof(FitnessDBContext))]
    [Migration("20241103113805_ProperRecipeSeed4")]
    partial class ProperRecipeSeed4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessApp.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Data.Models.Diet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Calories")
                        .HasColumnType("int");

                    b.Property<int?>("Carbohydrates")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("Fats")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("Protein")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Diets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a2b3c4d-5e6f-7a8b-9c0d-e1f2a3b4c5d6"),
                            Calories = 0,
                            Carbohydrates = 0,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A well-balanced diet for healthy living.",
                            Fats = 0,
                            Name = "Balanced Diet",
                            Protein = 0
                        },
                        new
                        {
                            Id = new Guid("2b3c4d5e-6f7a-8b9c-0de1-f2a3b4c5d6e7"),
                            Calories = 0,
                            Carbohydrates = 0,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ideal for muscle growth and recovery.",
                            Fats = 0,
                            Name = "High-Protein Diet",
                            Protein = 0
                        },
                        new
                        {
                            Id = new Guid("3c4d5e6f-7a8b-9c0d-e1f2-3a4b5c6d7e8f"),
                            Calories = 0,
                            Carbohydrates = 0,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A low-carb diet to promote weight loss.",
                            Fats = 0,
                            ImageUrl = "https://tasteforlife.com/sites/default/files/styles/laptop/public/diet-nutrition/special-diets/low-carb-diets-for-health-benefits/low-carb-diets-for-health-benefits.jpg?itok=saTbKWSP",
                            Name = "Low-Carb Diet",
                            Protein = 0
                        });
                });

            modelBuilder.Entity("FitnessApp.Data.Models.DietRecipe", b =>
                {
                    b.Property<Guid>("DietId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DietId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("DietsRecipes");

                    b.HasData(
                        new
                        {
                            DietId = new Guid("1a2b3c4d-5e6f-7a8b-9c0d-e1f2a3b4c5d6"),
                            RecipeId = new Guid("7fcf8f67-0b44-4be5-9f55-3fd8f0bcb4d1")
                        },
                        new
                        {
                            DietId = new Guid("1a2b3c4d-5e6f-7a8b-9c0d-e1f2a3b4c5d6"),
                            RecipeId = new Guid("c1d5a8e3-9a7a-4d77-bb38-8aafd82df021")
                        },
                        new
                        {
                            DietId = new Guid("2b3c4d5e-6f7a-8b9c-0de1-f2a3b4c5d6e7"),
                            RecipeId = new Guid("e3f7d4b7-94b2-4b3f-889e-8d7e5cdef921")
                        },
                        new
                        {
                            DietId = new Guid("2b3c4d5e-6f7a-8b9c-0de1-f2a3b4c5d6e7"),
                            RecipeId = new Guid("f3a7d8d2-1b9d-4c31-995a-6fa4fd0b032a")
                        },
                        new
                        {
                            DietId = new Guid("3c4d5e6f-7a8b-9c0d-e1f2-3a4b5c6d7e8f"),
                            RecipeId = new Guid("a6c8d4e0-1c8f-4f1b-b0c2-6a6d9a7a1f2a")
                        },
                        new
                        {
                            DietId = new Guid("3c4d5e6f-7a8b-9c0d-e1f2-3a4b5c6d7e8f"),
                            RecipeId = new Guid("a7f2e8d4-8b2e-41e8-90d7-5e2e6b7a2f5e")
                        },
                        new
                        {
                            DietId = new Guid("3c4d5e6f-7a8b-9c0d-e1f2-3a4b5c6d7e8f"),
                            RecipeId = new Guid("a823fb5b-9ed5-4d90-9c31-2398dcdb78de")
                        });
                });

            modelBuilder.Entity("FitnessApp.Data.Models.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bfc4e908-2f9f-4f2f-99bb-a1d462eae20f"),
                            CreatedOn = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 1,
                            IsDeleted = false,
                            MuscleGroup = 1,
                            Name = "Push-Up"
                        },
                        new
                        {
                            Id = new Guid("29d3278f-fb37-45a8-a7b6-41e6636e2e02"),
                            CreatedOn = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 2,
                            IsDeleted = false,
                            MuscleGroup = 2,
                            Name = "Pull-Up"
                        },
                        new
                        {
                            Id = new Guid("ab4c987e-6444-4c3f-b967-1ec2ffce9bd9"),
                            CreatedOn = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 1,
                            IsDeleted = false,
                            MuscleGroup = 3,
                            Name = "Squat"
                        },
                        new
                        {
                            Id = new Guid("b7c4a2b9-dfb2-4b6e-b7f7-58b5d33a0f34"),
                            CreatedOn = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 0,
                            IsDeleted = false,
                            MuscleGroup = 0,
                            Name = "Bicep Curl"
                        },
                        new
                        {
                            Id = new Guid("db8d4f5e-3f5f-4bfe-9b53-8171b4c77f8b"),
                            CreatedOn = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 3,
                            IsDeleted = false,
                            MuscleGroup = 2,
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = new Guid("cce872f8-19f8-4e7d-bd57-e7f5c66a06b7"),
                            CreatedOn = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 2,
                            IsDeleted = false,
                            MuscleGroup = 1,
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = new Guid("96d3e1b7-7806-4f54-bc58-5d8b9d8a7f1f"),
                            CreatedOn = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 0,
                            IsDeleted = false,
                            MuscleGroup = 0,
                            Name = "Hammer Curl"
                        },
                        new
                        {
                            Id = new Guid("fd3e8bc1-a4a6-4535-91f9-e4e68e0cde90"),
                            CreatedOn = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 1,
                            IsDeleted = false,
                            MuscleGroup = 0,
                            Name = "Concentration Curl"
                        },
                        new
                        {
                            Id = new Guid("2a8ed1d9-84d3-4fd4-83e2-2c4391f0b01b"),
                            CreatedOn = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 1,
                            IsDeleted = false,
                            MuscleGroup = 0,
                            Name = "Tricep Extension"
                        },
                        new
                        {
                            Id = new Guid("69b1df3e-1e34-44f3-8e3b-dca7eb9b2f3f"),
                            CreatedOn = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 2,
                            IsDeleted = false,
                            MuscleGroup = 1,
                            Name = "Dumbbell Fly"
                        },
                        new
                        {
                            Id = new Guid("b6a7ecb8-5e4e-4372-8d6d-f63b0c6e639e"),
                            CreatedOn = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 1,
                            IsDeleted = false,
                            MuscleGroup = 1,
                            Name = "Pec Deck"
                        },
                        new
                        {
                            Id = new Guid("fdcd4903-8d91-4091-91de-96b88b0a5f23"),
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 2,
                            IsDeleted = false,
                            MuscleGroup = 1,
                            Name = "Incline Bench Press"
                        },
                        new
                        {
                            Id = new Guid("d4f5b8b7-5638-4882-9254-07f5f35c09d6"),
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 1,
                            IsDeleted = false,
                            MuscleGroup = 2,
                            Name = "Lat Pulldown"
                        },
                        new
                        {
                            Id = new Guid("9b8de205-3c91-47f8-a6bc-46a6d2c48238"),
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 2,
                            IsDeleted = false,
                            MuscleGroup = 2,
                            Name = "T-Bar Row"
                        },
                        new
                        {
                            Id = new Guid("ccf2748a-492e-496e-bd6b-8df2dc9b8f4a"),
                            CreatedOn = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 2,
                            IsDeleted = false,
                            MuscleGroup = 2,
                            Name = "Bent Over Row"
                        },
                        new
                        {
                            Id = new Guid("4e8b7a3b-e5c1-4c73-95ab-27a05dcf2a31"),
                            CreatedOn = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 1,
                            IsDeleted = false,
                            MuscleGroup = 2,
                            Name = "Seated Row"
                        },
                        new
                        {
                            Id = new Guid("ff5e9f1a-8f9f-4a8f-9081-d17b9e6fbe3c"),
                            CreatedOn = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 0,
                            IsDeleted = false,
                            MuscleGroup = 2,
                            Name = "Back Extension"
                        },
                        new
                        {
                            Id = new Guid("c9b4f5f1-1e3d-4a93-9d42-bb27a1b4b315"),
                            CreatedOn = new DateTime(2023, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 1,
                            IsDeleted = false,
                            MuscleGroup = 3,
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = new Guid("b9c7e1d7-a9b2-4505-89c9-6cf8d87e2e6d"),
                            CreatedOn = new DateTime(2003, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 1,
                            IsDeleted = false,
                            MuscleGroup = 3,
                            Name = "Lunges"
                        },
                        new
                        {
                            Id = new Guid("1c6e0b2a-3b6a-4427-8df7-51d8a9f2a9a3"),
                            CreatedOn = new DateTime(2003, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 2,
                            IsDeleted = false,
                            MuscleGroup = 3,
                            Name = "Leg Extension"
                        },
                        new
                        {
                            Id = new Guid("3e6c1f4b-0e5d-4f8d-8b2b-1a0e37dce9b7"),
                            CreatedOn = new DateTime(2003, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 0,
                            IsDeleted = false,
                            MuscleGroup = 3,
                            Name = "Calf Raise"
                        },
                        new
                        {
                            Id = new Guid("dbb7b1c4-72e8-4a37-91a7-fb97d4b4f0e3"),
                            CreatedOn = new DateTime(2003, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 2,
                            IsDeleted = false,
                            MuscleGroup = 3,
                            Name = "Bulgarian Split Squat"
                        },
                        new
                        {
                            Id = new Guid("d3e0b5f7-a1b5-4207-81b3-e0a5f6e0e8b5"),
                            CreatedOn = new DateTime(2003, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 1,
                            IsDeleted = false,
                            MuscleGroup = 3,
                            Name = "Reverse Lunges"
                        },
                        new
                        {
                            Id = new Guid("3e9a5c5f-8d7e-4b2c-923b-27c4a6e2a6d7"),
                            CreatedOn = new DateTime(2003, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 1,
                            IsDeleted = false,
                            MuscleGroup = 3,
                            Name = "Step-Ups"
                        },
                        new
                        {
                            Id = new Guid("7e8c1e5b-0e6d-4b8d-8d2f-2a1e3c7dce8d"),
                            CreatedOn = new DateTime(2006, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 2,
                            IsDeleted = false,
                            MuscleGroup = 0,
                            Name = "Overhead Tricep Extension"
                        },
                        new
                        {
                            Id = new Guid("e2b1f3f7-8c1e-4b5f-9f2a-0e3c7d5b0d8d"),
                            CreatedOn = new DateTime(2016, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 2,
                            IsDeleted = false,
                            MuscleGroup = 0,
                            Name = "Skull Crusher"
                        },
                        new
                        {
                            Id = new Guid("f2c3d8a4-b1e8-4d2f-9c3e-4d8f2e3c1b0d"),
                            CreatedOn = new DateTime(2016, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 1,
                            IsDeleted = false,
                            MuscleGroup = 0,
                            Name = "Cable Curl"
                        },
                        new
                        {
                            Id = new Guid("8c3d6a7b-e1f2-4c3b-9d3e-0e3c4f5a1b2d"),
                            CreatedOn = new DateTime(2016, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 2,
                            IsDeleted = false,
                            MuscleGroup = 1,
                            Name = "Close-Grip Bench Press"
                        },
                        new
                        {
                            Id = new Guid("1e5b9a3c-2d8e-4c7d-9d3e-4d8f2c3e1b6f"),
                            CreatedOn = new DateTime(2018, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulty = 2,
                            IsDeleted = false,
                            MuscleGroup = 1,
                            Name = "Decline Bench Press"
                        });
                });

            modelBuilder.Entity("FitnessApp.Data.Models.Progress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Progresses");
                });

            modelBuilder.Entity("FitnessApp.Data.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<int>("Carbohydrates")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fats")
                        .HasColumnType("int");

                    b.Property<int>("Goal")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Preparation")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("Protein")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("23d3e7f0-2d8f-4fc3-8a3a-8f9b6a6c2e93"),
                            Calories = 350,
                            Carbohydrates = 45,
                            CreatedOn = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 8,
                            Goal = 2,
                            ImageUrl = "https://www.whollytasteful.com/wp-content/uploads/2022/09/protein-pancakes-with-oats-featured.jpg",
                            Ingredients = "Oats, banana, protein powder, eggs",
                            IsDeleted = false,
                            Name = "Protein Pancakes",
                            Preparation = "In a blender, combine the oats, banana, protein powder, and eggs. Blend until the mixture is smooth and free of lumps. Heat a non-stick pan over medium heat and lightly coat it with cooking spray. Pour a small amount of the batter onto the pan and cook for 2-3 minutes until bubbles appear on the surface. Flip the pancake and cook for an additional 2 minutes on the other side. Serve warm, topped with fresh berries or a drizzle of honey for added flavor.",
                            Protein = 25
                        },
                        new
                        {
                            Id = new Guid("7fcf8f67-0b44-4be5-9f55-3fd8f0bcb4d1"),
                            Calories = 450,
                            Carbohydrates = 55,
                            CreatedOn = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 10,
                            Goal = 0,
                            ImageUrl = "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/13385.jpg",
                            Ingredients = "Chicken breast, brown rice, broccoli",
                            IsDeleted = false,
                            Name = "Chicken and Rice",
                            Preparation = "Start by seasoning the chicken breast with salt, pepper, and your favorite spices. Heat a grill pan over medium heat and cook the chicken for about 5-6 minutes on each side, or until fully cooked. Meanwhile, bring a pot of water to a boil and add the brown rice, cooking for about 30-35 minutes until tender. Steam the broccoli for 5-7 minutes, until it is bright green and slightly tender. Serve the grilled chicken over the rice with a side of steamed broccoli. Optionally, drizzle with a little olive oil or lemon juice.",
                            Protein = 35
                        },
                        new
                        {
                            Id = new Guid("c1d5a8e3-9a7a-4d77-bb38-8aafd82df021"),
                            Calories = 600,
                            Carbohydrates = 75,
                            CreatedOn = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 20,
                            Goal = 0,
                            ImageUrl = "https://storage.googleapis.com/ayuvya_images/blog_image/5_Best_Smoothie_Recipes_for_Weight_Gain_You_Need_to_Try_Now.webp",
                            Ingredients = "Milk, banana, peanut butter, protein powder, oats, honey",
                            IsDeleted = false,
                            Name = "Mass-Gain Smoothie",
                            Preparation = "1. Pour 1 cup of milk into a blender. Add a peeled banana, 2 tablespoons of peanut butter, 1 scoop of protein powder, 1/4 cup of oats, and 1 tablespoon of honey. 2. Blend all ingredients on high until the mixture is smooth and creamy, ensuring no chunks remain. 3. Taste and adjust sweetness with more honey if needed. 4. Pour into a large glass and serve chilled. Enjoy immediately for the best texture and flavor.",
                            Protein = 30
                        },
                        new
                        {
                            Id = new Guid("e3f7d4b7-94b2-4b3f-889e-8d7e5cdef921"),
                            Calories = 650,
                            Carbohydrates = 50,
                            CreatedOn = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 28,
                            Goal = 1,
                            ImageUrl = "https://dianasdelishdishes.com/wp-content/uploads/2023/06/C42B7659-56C9-42D0-BF0E-0A34B78BE0A5.jpeg",
                            Ingredients = "Ground beef, sweet potato, olive oil, spinach, garlic, salt, pepper",
                            IsDeleted = false,
                            Name = "Beef and Sweet Potato Power Bowl",
                            Preparation = "1. Preheat the oven to 400°F (200°C). 2. Peel and cube the sweet potato, then toss with 1 tablespoon of olive oil, salt, and pepper. 3. Spread the cubes on a baking sheet and roast for 20-25 minutes, turning halfway, until tender and golden. 4. While the sweet potato cooks, heat a skillet over medium heat and add 1 tablespoon of olive oil. 5. Add 1 minced garlic clove, cooking until fragrant. Add the ground beef, seasoning with salt and pepper, and cook until browned, breaking it apart as it cooks. 6. Remove the beef from the heat and set aside. 7. In the same pan, lightly sauté a handful of spinach until wilted. 8. In a bowl, layer the roasted sweet potatoes, beef, and spinach, adding more seasoning if desired. Serve warm.",
                            Protein = 40
                        },
                        new
                        {
                            Id = new Guid("f3a7d8d2-1b9d-4c31-995a-6fa4fd0b032a"),
                            Calories = 480,
                            Carbohydrates = 40,
                            CreatedOn = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 15,
                            Goal = 1,
                            ImageUrl = "https://tastesbetterfromscratch.com/wp-content/uploads/2014/03/Chicken-Bacon-Avocado-Wrap-1.jpg",
                            Ingredients = "Grilled chicken breast, whole wheat wrap, avocado, tomato, lettuce, Greek yogurt",
                            IsDeleted = false,
                            Name = "Chicken Avocado Wrap",
                            Preparation = "1. Slice the grilled chicken breast into thin strips. 2. Warm the whole wheat wrap in a dry skillet over medium heat for 1-2 minutes on each side. 3. While the wrap warms, peel and mash 1/2 avocado in a bowl until smooth. 4. Spread a thin layer of Greek yogurt onto the center of the warm wrap. 5. Add the sliced chicken, mashed avocado, tomato slices, and a handful of lettuce. 6. Season with salt and pepper to taste. 7. Fold the bottom of the wrap up, then roll tightly from one side to the other. 8. Cut in half and enjoy immediately.",
                            Protein = 30
                        },
                        new
                        {
                            Id = new Guid("a6c8d4e0-1c8f-4f1b-b0c2-6a6d9a7a1f2a"),
                            Calories = 300,
                            Carbohydrates = 20,
                            CreatedOn = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 10,
                            Goal = 1,
                            ImageUrl = "https://www.foodiecrush.com/wp-content/uploads/2016/08/Linguine-and-Zucchini-Noodles-with-Shrimp-foodiecrush.com-0014.jpg",
                            Ingredients = "Zucchini, shrimp, garlic, olive oil, cherry tomatoes, parsley, salt, pepper",
                            IsDeleted = false,
                            Name = "Zucchini Noodles with Grilled Shrimp",
                            Preparation = "1. Use a spiralizer to turn 2 zucchinis into noodles. Set aside. 2. Season the shrimp with salt, pepper, and a minced garlic clove. 3. Heat 1 tablespoon of olive oil in a skillet over medium heat, then add the shrimp. Cook for 2-3 minutes per side until pink and opaque. Remove from the skillet and set aside. 4. In the same skillet, add more garlic and sauté until fragrant. 5. Add the zucchini noodles and cherry tomatoes, cooking for 2-3 minutes until slightly softened. 6. Return the shrimp to the skillet, toss with the noodles, and garnish with chopped parsley. Serve warm.",
                            Protein = 25
                        },
                        new
                        {
                            Id = new Guid("a7f2e8d4-8b2e-41e8-90d7-5e2e6b7a2f5e"),
                            Calories = 150,
                            Carbohydrates = 3,
                            CreatedOn = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 5,
                            Goal = 1,
                            ImageUrl = "https://images.eatthismuch.com/img/906792_tabitharwheeler_7ecdcbb2-52e2-456d-8c38-4194febe4830.jpg",
                            Ingredients = "Egg whites, spinach, bell pepper, olive oil, salt, pepper",
                            IsDeleted = false,
                            Name = "Egg White Omelet with Spinach",
                            Preparation = "1. Whisk together 4 egg whites with a pinch of salt and pepper. 2. Heat 1 teaspoon of olive oil in a non-stick skillet over medium heat. 3. Add a handful of spinach and diced bell pepper to the skillet, cooking until the spinach wilts. 4. Pour the egg whites over the vegetables and cook for 2-3 minutes until the bottom sets. 5. Carefully fold the omelet in half and cook for another minute. 6. Slide the omelet onto a plate and serve immediately.",
                            Protein = 20
                        },
                        new
                        {
                            Id = new Guid("a823fb5b-9ed5-4d90-9c31-2398dcdb78de"),
                            Calories = 500,
                            Carbohydrates = 30,
                            CreatedOn = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 20,
                            Goal = 0,
                            ImageUrl = "https://www.rachelcooks.com/wp-content/uploads/2022/09/Beef-Stir-Fry-with-Vegetables016-web-square.jpg",
                            Ingredients = "Beef, bell peppers, onions, soy sauce",
                            IsDeleted = false,
                            Name = "Beef Stir-Fry",
                            Preparation = "Slice the beef thinly across the grain and season it with a pinch of salt and pepper. Heat a tablespoon of oil in a large skillet over medium-high heat. Add the beef and cook for 3-4 minutes until browned. Remove the beef and set aside. In the same skillet, add the sliced bell peppers and onions, cooking for about 5 minutes until tender. Add the beef back to the skillet along with soy sauce and a touch of honey or brown sugar for sweetness. Stir everything together and cook for another 2 minutes. Serve hot over rice or noodles.",
                            Protein = 40
                        },
                        new
                        {
                            Id = new Guid("b2175cd6-6822-4e93-917f-3e8c70c09fbc"),
                            Calories = 300,
                            Carbohydrates = 45,
                            CreatedOn = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 8,
                            Goal = 2,
                            ImageUrl = "https://images.getrecipekit.com/20230919180123-greek-20yogurt-20parfait.png?aspect_ratio=1:1&quality=90&",
                            Ingredients = "Greek yogurt, berries, honey, granola",
                            IsDeleted = false,
                            Name = "Greek Yogurt Parfait",
                            Preparation = "In a glass or bowl, start by adding a layer of Greek yogurt at the bottom. Next, add a layer of fresh berries like strawberries, blueberries, or raspberries. Drizzle a teaspoon of honey over the berries to add a touch of sweetness. Add a layer of granola for crunch. Repeat the layers until the glass or bowl is filled, finishing with a few berries and a final drizzle of honey on top. Serve immediately for a refreshing and protein-packed breakfast or snack.",
                            Protein = 15
                        },
                        new
                        {
                            Id = new Guid("ce451c31-e002-4e97-9140-dc81837b58a7"),
                            Calories = 250,
                            Carbohydrates = 30,
                            CreatedOn = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 4,
                            Goal = 0,
                            ImageUrl = "https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/1D1F8AE8-0888-45CB-B21B-15377ADC6C9A/Derivates/874a16dd-d1b1-4db0-bc13-fab251938451.jpg",
                            Ingredients = "Protein powder, almond milk, banana, spinach",
                            IsDeleted = false,
                            Name = "Protein Smoothie",
                            Preparation = "In a blender, add one scoop of protein powder, a cup of almond milk, a ripe banana, and a handful of fresh spinach leaves. Blend on high until the mixture is completely smooth and no chunks remain. Taste the smoothie and add a bit of honey if you want extra sweetness. For a colder smoothie, you can add a few ice cubes or use a frozen banana. Pour into a glass and enjoy immediately for a nutritious breakfast or post-workout snack.",
                            Protein = 20
                        },
                        new
                        {
                            Id = new Guid("37df0c76-9487-4d99-9b18-f5c30c4ffcb3"),
                            Calories = 200,
                            Carbohydrates = 5,
                            CreatedOn = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 15,
                            Goal = 2,
                            ImageUrl = "https://tealnotes.com/wp-content/uploads/2023/05/Featured-Image-46-800x530.png",
                            Ingredients = "Eggs, salt, bell pepper, spinach",
                            IsDeleted = false,
                            Name = "Scrambled Eggs with Veggies",
                            Preparation = "Crack the eggs into a bowl, add a pinch of salt, and whisk until smooth. Heat a small amount of olive oil in a non-stick skillet over medium heat. Add diced bell pepper and cook for 2-3 minutes until softened. Add the spinach and cook until wilted, about 1 minute. Pour the eggs into the pan and gently stir with a spatula, folding the eggs over themselves until just set. Remove from heat while the eggs are still slightly soft. Serve hot, garnished with fresh herbs if desired.",
                            Protein = 12
                        },
                        new
                        {
                            Id = new Guid("ab237e7b-08f2-4dcd-b6f9-98a65c96f6ec"),
                            Calories = 300,
                            Carbohydrates = 10,
                            CreatedOn = new DateTime(2024, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 12,
                            Goal = 1,
                            ImageUrl = "https://tastythin.com/wp-content/uploads/2020/02/asian-turkey-lettuce-wraps2-500x500.jpg",
                            Ingredients = "Ground turkey, lettuce, tomatoes, avocado",
                            IsDeleted = false,
                            Name = "Turkey Lettuce Wraps",
                            Preparation = "In a skillet over medium heat, cook the ground turkey until browned, breaking it up with a spoon as it cooks. Season with salt, pepper, and a dash of cumin if desired. Wash and dry large lettuce leaves, which will serve as the wraps. Once the turkey is cooked through, spoon it into each lettuce leaf and top with diced tomatoes and sliced avocado. Serve immediately for a low-carb, high-protein meal.",
                            Protein = 28
                        },
                        new
                        {
                            Id = new Guid("ef63dc7f-bb29-4c6c-bcf5-4732ab2f4921"),
                            Calories = 350,
                            Carbohydrates = 12,
                            CreatedOn = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 15,
                            Goal = 1,
                            ImageUrl = "https://www.thespruceeats.com/thmb/1HuTabE4tSdTe8YDcdiR2ts2P3Y=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/california-grilled-chicken-salad-recipe-334159-13-8ecd934fee5e42f8b5d38239b083460b.jpg",
                            Ingredients = "Chicken breast, lettuce, cucumber, tomatoes, olive oil",
                            IsDeleted = false,
                            Name = "Grilled Chicken Salad",
                            Preparation = "Season the chicken breast with salt, pepper, and a bit of garlic powder. Heat a grill pan over medium heat and cook the chicken breast for 6-7 minutes on each side, until fully cooked. Let the chicken cool slightly, then slice it thinly. In a large bowl, combine chopped lettuce, cucumber, and tomatoes. Drizzle with olive oil and toss to coat. Top with sliced chicken and serve with a light vinaigrette or dressing of your choice.",
                            Protein = 35
                        },
                        new
                        {
                            Id = new Guid("e073b44d-417e-4b9e-85d8-5a9536185b68"),
                            Calories = 450,
                            Carbohydrates = 65,
                            CreatedOn = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 15,
                            Goal = 2,
                            ImageUrl = "https://cdn.loveandlemons.com/wp-content/uploads/2023/05/quinoa-bowl-recipe.jpg",
                            Ingredients = "Quinoa, black beans, corn, avocado, lime",
                            IsDeleted = false,
                            Name = "Quinoa Bowl",
                            Preparation = "Cook quinoa according to package instructions. In a large bowl, combine cooked quinoa, rinsed black beans, corn, and diced avocado. Squeeze fresh lime juice over the top and toss gently to combine. Season with salt and pepper to taste. For added flavor, you can also add chopped cilantro or diced jalapeño. Serve chilled or at room temperature as a nutritious and filling meal.",
                            Protein = 15
                        },
                        new
                        {
                            Id = new Guid("8e22c1d5-0c6e-47c7-bc25-559518fe4f24"),
                            Calories = 200,
                            Carbohydrates = 5,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 10,
                            Goal = 1,
                            ImageUrl = "https://littlespoonfarm.com/wp-content/uploads/2021/08/tuna-salad-recipe-card.jpg",
                            Ingredients = "Canned tuna, mayo, celery, lettuce",
                            IsDeleted = false,
                            Name = "Tuna Salad",
                            Preparation = "In a bowl, mix drained canned tuna with a tablespoon of mayo and diced celery. Season with salt and pepper to taste. Place a scoop of the tuna mixture on a bed of fresh lettuce leaves. You can also add diced tomatoes or cucumbers for extra crunch. Serve cold as a quick lunch or snack.",
                            Protein = 25
                        },
                        new
                        {
                            Id = new Guid("c670818c-d46f-440b-9332-0f0d01937887"),
                            Calories = 400,
                            Carbohydrates = 35,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 18,
                            Goal = 1,
                            ImageUrl = "https://mojo.generalmills.com/api/public/content/wD6Zdi1fS0OIerKfD62IBA_webp_base.webp?v=baa249d0&t=191ddcab8d1c415fa10fa00a14351227",
                            Ingredients = "Bell peppers, ground beef, rice, cheese",
                            IsDeleted = false,
                            Name = "Stuffed Peppers",
                            Preparation = "Preheat the oven to 375°F (190°C). Slice the tops off the bell peppers and remove the seeds. In a skillet, brown the ground beef over medium heat. Mix in cooked rice and season with salt, pepper, and Italian herbs. Stuff the mixture into each bell pepper and place them in a baking dish. Top with shredded cheese and bake for about 25-30 minutes until the peppers are tender and the cheese is bubbly.",
                            Protein = 25
                        },
                        new
                        {
                            Id = new Guid("7a88e34d-b5ba-4717-b1c1-5348d8d2a3ef"),
                            Calories = 300,
                            Carbohydrates = 5,
                            CreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 20,
                            Goal = 2,
                            ImageUrl = "https://heavenlyhomecooking.com/wp-content/uploads/2021/04/Vegetable-Omelette-Recipe-Featured-1.jpg",
                            Ingredients = "Eggs, bell peppers, cheese, spinach",
                            IsDeleted = false,
                            Name = "Veggie Omelette",
                            Preparation = "Whisk the eggs in a bowl and season with salt and pepper. Heat a non-stick skillet over medium heat and add a little oil. Pour in the eggs and let them cook for about 1-2 minutes until the edges start to set. Add diced bell peppers and cheese on one half of the omelette. Carefully fold the other half over the filling and cook for another minute until the cheese melts and the eggs are fully cooked. Serve hot with a side of toast or fresh fruit.",
                            Protein = 18
                        },
                        new
                        {
                            Id = new Guid("53fa075b-fc37-46bc-b50f-c4d60013ef7a"),
                            Calories = 400,
                            Carbohydrates = 8,
                            CreatedOn = new DateTime(2024, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 22,
                            Goal = 1,
                            ImageUrl = "https://saltpepperskillet.com/wp-content/uploads/oven-baked-salmon-on-sheet-pan-horizontal-1.jpg",
                            Ingredients = "Salmon fillet, lemon, herbs, asparagus",
                            IsDeleted = false,
                            Name = "Baked Salmon",
                            Preparation = "Preheat the oven to 400°F (200°C). Place the salmon fillet on a baking sheet lined with parchment paper. Squeeze fresh lemon juice over the top and sprinkle with herbs like dill or parsley. Arrange asparagus around the salmon and drizzle with olive oil. Bake for about 15-20 minutes until the salmon is cooked through and flakes easily with a fork. Serve warm with a side of your choice.",
                            Protein = 40
                        },
                        new
                        {
                            Id = new Guid("eb4ad19e-e048-4630-bb57-2ee9c470de79"),
                            Calories = 250,
                            Carbohydrates = 30,
                            CreatedOn = new DateTime(2024, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 10,
                            Goal = 2,
                            ImageUrl = "https://cdn.loveandlemons.com/wp-content/uploads/2023/05/chickpea-salad-500x500.jpg",
                            Ingredients = "Chickpeas, cucumber, tomatoes, lemon, olive oil",
                            IsDeleted = false,
                            Name = "Chickpea Salad",
                            Preparation = "In a bowl, combine drained chickpeas, diced cucumber, and chopped tomatoes. Drizzle with lemon juice and olive oil, and season with salt and pepper. Toss everything together until well mixed. This salad can be served immediately or chilled for a refreshing side dish or light meal.",
                            Protein = 12
                        },
                        new
                        {
                            Id = new Guid("fb3e4329-2c05-49cc-9c19-6ff56464918b"),
                            Calories = 200,
                            Carbohydrates = 32,
                            CreatedOn = new DateTime(2024, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 8,
                            Goal = 1,
                            ImageUrl = "https://www.kitchensanctuary.com/wp-content/uploads/2021/10/Sweet-Potato-Fries-wideFS-20.webp",
                            Ingredients = "Sweet potatoes, olive oil, salt, pepper",
                            IsDeleted = false,
                            Name = "Sweet Potato Fries",
                            Preparation = "Preheat the oven to 425°F (220°C). Cut sweet potatoes into thin strips and place them in a bowl. Drizzle with olive oil, salt, and pepper, and toss to coat evenly. Spread the sweet potatoes on a baking sheet lined with parchment paper in a single layer. Bake for 20-25 minutes until they are crispy and golden, flipping halfway through. Serve hot as a side dish or snack.",
                            Protein = 3
                        },
                        new
                        {
                            Id = new Guid("19bdb4c8-3731-4456-8e8e-5e0d174b3241"),
                            Calories = 350,
                            Carbohydrates = 30,
                            CreatedOn = new DateTime(2024, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 20,
                            Goal = 2,
                            ImageUrl = "https://www.allrecipes.com/thmb/8NccFzsaq0_OZPDKmf7Yee-aG78=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/AvocadoToastwithEggFranceC4x3-bb87e3bbf1944657b7db35f1383fabdb.jpg",
                            Ingredients = "Bread, avocado, salt, pepper, lemon",
                            IsDeleted = false,
                            Name = "Avocado Toast",
                            Preparation = "Toast the bread to your desired crispiness. Mash the avocado in a bowl and season with salt, pepper, and a squeeze of lemon juice. Spread the mashed avocado over the toasted bread. Optional toppings include sliced tomatoes, radishes, or a poached egg.",
                            Protein = 10
                        },
                        new
                        {
                            Id = new Guid("fb3e4329-2c05-49cc-9c19-6ff564649118"),
                            Calories = 200,
                            Carbohydrates = 25,
                            CreatedOn = new DateTime(2024, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 10,
                            Goal = 2,
                            ImageUrl = "https://simple-veganista.com/wp-content/uploads/2017/04/chocolate-chia-pudding-1.jpg",
                            Ingredients = "Chia seeds, almond milk, cocoa powder, honey",
                            IsDeleted = false,
                            Name = "Chocolate Chia Pudding",
                            Preparation = "In a bowl, mix chia seeds, cocoa powder, and almond milk. Stir well to combine and ensure there are no clumps. Add honey for sweetness. Cover and refrigerate for at least 4 hours or overnight until it thickens. Serve chilled, topped with fruit or nuts.",
                            Protein = 5
                        },
                        new
                        {
                            Id = new Guid("29b2d59e-5ac9-46cd-bbb3-4b235e5bff0f"),
                            Calories = 300,
                            Carbohydrates = 40,
                            CreatedOn = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 10,
                            Goal = 2,
                            ImageUrl = "https://assets.bonappetit.com/photos/5a05c9df3388d32a6ed54e97/1:1/w_2560%2Cc_limit/curried-lentil-tomato-and-coconut-soup.jpg",
                            Ingredients = "Lentils, coconut milk, curry powder, vegetables",
                            IsDeleted = false,
                            Name = "Coconut Curry Lentil Soup",
                            Preparation = "In a pot, sauté chopped vegetables until soft. Add lentils, coconut milk, curry powder, and water. Bring to a boil, then reduce heat and simmer until lentils are tender, about 20-25 minutes. Season with salt and pepper to taste.",
                            Protein = 15
                        },
                        new
                        {
                            Id = new Guid("3f9f14b8-bba3-4f57-b407-d4eb33c1f789"),
                            Calories = 200,
                            Carbohydrates = 10,
                            CreatedOn = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 15,
                            Goal = 1,
                            ImageUrl = "https://www.sweetashoney.co/wp-content/uploads/Zucchini-Noodles-With-Pesto-2-1.jpg",
                            Ingredients = "Zucchini, pesto, cherry tomatoes, olive oil",
                            IsDeleted = false,
                            Name = "Zucchini Noodles with Pesto",
                            Preparation = "Spiralize zucchini into noodles. In a skillet, heat olive oil over medium heat and add zucchini noodles, cooking for 2-3 minutes until slightly softened. Stir in pesto and halved cherry tomatoes. Cook for an additional 2 minutes. Serve warm.",
                            Protein = 5
                        },
                        new
                        {
                            Id = new Guid("a0e4a4a4-4b43-48b7-9173-f84a3f1d52a1"),
                            Calories = 400,
                            Carbohydrates = 52,
                            CreatedOn = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 18,
                            Goal = 0,
                            ImageUrl = "https://www.simplyrecipes.com/thmb/gjS-FSuYnqK3fclkE2fWhYl1VWQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Spaghetti-Aglio-e-Olio-LEAD-2-c8e7e8c6edb04a8691463c6ea8cd4ba1.jpg",
                            Ingredients = "Spaghetti, garlic, olive oil, red pepper flakes",
                            IsDeleted = false,
                            Name = "Spaghetti Aglio e Olio",
                            Preparation = "Cook spaghetti according to package instructions. In a skillet, heat olive oil over medium heat, and add thinly sliced garlic. Sauté until golden. Add red pepper flakes and drained spaghetti. Toss to coat and serve immediately.",
                            Protein = 12
                        },
                        new
                        {
                            Id = new Guid("71c3c77c-e826-47c5-92d0-88c42d22b867"),
                            Calories = 300,
                            Carbohydrates = 30,
                            CreatedOn = new DateTime(2024, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 12,
                            Goal = 0,
                            ImageUrl = "https://www.nutritiousdeliciousness.com/wp-content/uploads/2024/02/Asian-Shrimp-Tacos1.jpg",
                            Ingredients = "Shrimp, corn tortillas, cabbage, lime",
                            IsDeleted = false,
                            Name = "Shrimp Tacos",
                            Preparation = "Season shrimp with salt and pepper. In a skillet, cook shrimp over medium heat until pink, about 2-3 minutes per side. Warm corn tortillas in a separate pan. Assemble tacos by placing shrimp on tortillas, topping with shredded cabbage, and squeezing lime juice over them.",
                            Protein = 25
                        },
                        new
                        {
                            Id = new Guid("60e4a005-500e-4973-9d71-1b5c462f7de5"),
                            Calories = 350,
                            Carbohydrates = 30,
                            CreatedOn = new DateTime(2024, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 15,
                            Goal = 0,
                            ImageUrl = "https://onebalancedlife.com/wp-content/uploads/2020/08/Breakfast-Wrap-scaled-720x720.jpg",
                            Ingredients = "Eggs, spinach, whole wheat wrap, cheese",
                            IsDeleted = false,
                            Name = "Egg and Spinach Breakfast Wrap",
                            Preparation = "Whisk the eggs in a bowl. In a skillet, cook spinach until wilted. Add eggs and cook, stirring gently. Place the egg and spinach mixture on a whole wheat wrap, sprinkle with cheese, and roll tightly. Serve warm.",
                            Protein = 25
                        },
                        new
                        {
                            Id = new Guid("dd638b57-0b70-46a7-8aeb-bf8c8025c222"),
                            Calories = 450,
                            Carbohydrates = 30,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 25,
                            Goal = 0,
                            ImageUrl = "https://img.chefkoch-cdn.de/rezepte/1578671265353584/bilder/1509269/crop-960x540/chili-con-carne.jpg",
                            Ingredients = "Ground beef, kidney beans, tomatoes, chili powder",
                            IsDeleted = false,
                            Name = "Chili Con Carne",
                            Preparation = "In a pot, brown ground beef over medium heat. Add diced tomatoes, kidney beans, and chili powder. Simmer for 30 minutes, stirring occasionally. Serve hot, garnished with chopped cilantro or cheese.",
                            Protein = 30
                        },
                        new
                        {
                            Id = new Guid("90f40e3b-b5eb-4899-b365-d4a2f94f1281"),
                            Calories = 200,
                            Carbohydrates = 15,
                            CreatedOn = new DateTime(2024, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 8,
                            Goal = 1,
                            ImageUrl = "https://www.kitchensanctuary.com/wp-content/uploads/2020/09/Cauliflower-Egg-Fried-Rice-square-FS-14.jpg",
                            Ingredients = "Cauliflower, peas, carrots, soy sauce",
                            IsDeleted = false,
                            Name = "Cauliflower Fried Rice",
                            Preparation = "Grate cauliflower to create rice-sized pieces. In a skillet, heat oil and sauté peas and carrots until tender. Add cauliflower rice and soy sauce. Cook for 5-7 minutes, stirring frequently. Serve hot.",
                            Protein = 5
                        },
                        new
                        {
                            Id = new Guid("af3f84d1-9f18-4c65-bb8c-04d15c9e2294"),
                            Calories = 250,
                            Carbohydrates = 35,
                            CreatedOn = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 10,
                            Goal = 1,
                            ImageUrl = "https://www.nospoonnecessary.com/wp-content/uploads/2020/03/Beans-for-Tacos-recipe.jpg",
                            Ingredients = "Black beans, corn tortillas, avocado, salsa",
                            IsDeleted = false,
                            Name = "Black Bean Tacos",
                            Preparation = "In a bowl, mash black beans and season with lime juice. Warm corn tortillas in a skillet. Assemble tacos by filling tortillas with black bean mixture, diced avocado, and salsa. Serve with lime wedges.",
                            Protein = 10
                        },
                        new
                        {
                            Id = new Guid("be29b72f-3f75-49d0-bb69-7d1e54aab95a"),
                            Calories = 400,
                            Carbohydrates = 50,
                            CreatedOn = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 15,
                            Goal = 1,
                            ImageUrl = "https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_4:3/k%2FPhoto%2FRecipes%2F2019-11-recipe-mediterranean-quinoa-salad%2F2019-10-21_Kitchn89095_Mediteranean-Quinoa-Salad",
                            Ingredients = "Quinoa, cherry tomatoes, cucumber, feta cheese",
                            IsDeleted = false,
                            Name = "Quinoa Salad",
                            Preparation = "Cook quinoa according to package instructions. In a bowl, combine cooked quinoa, halved cherry tomatoes, diced cucumber, and crumbled feta cheese. Drizzle with olive oil and lemon juice, then toss to combine.",
                            Protein = 12
                        },
                        new
                        {
                            Id = new Guid("a1c1a9cd-25f5-4c19-89f6-32851f0d1152"),
                            Calories = 350,
                            Carbohydrates = 20,
                            CreatedOn = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 10,
                            Goal = 0,
                            ImageUrl = "https://i2.wp.com/www.downshiftology.com/wp-content/uploads/2021/05/Chicken-Stir-Fry-main-1.jpg",
                            Ingredients = "Chicken breast, mixed vegetables, soy sauce, ginger",
                            IsDeleted = false,
                            Name = "Chicken Stir-Fry",
                            Preparation = "In a skillet, heat oil over medium-high heat. Add diced chicken breast and cook until browned. Add mixed vegetables and ginger. Stir-fry for 5-7 minutes, then add soy sauce and cook for another 2 minutes. Serve hot.",
                            Protein = 30
                        },
                        new
                        {
                            Id = new Guid("d2155f29-4a5a-4e71-a1ef-cb493b45bc4d"),
                            Calories = 500,
                            Carbohydrates = 70,
                            CreatedOn = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 15,
                            Goal = 2,
                            ImageUrl = "https://thestayathomechef.com/wp-content/uploads/2021/01/Mediterranean-Chickpea-Salad-1-1200x720.jpg",
                            Ingredients = "Chickpeas, brown rice, cucumber, tahini",
                            IsDeleted = false,
                            Name = "Mediterranean Chickpea Bowl",
                            Preparation = "Cook brown rice according to package instructions. In a bowl, combine cooked rice, chickpeas, diced cucumber, and a drizzle of tahini. Top with lemon juice and fresh parsley.",
                            Protein = 20
                        },
                        new
                        {
                            Id = new Guid("816b8eec-5ff7-408e-a903-55f509b97302"),
                            Calories = 450,
                            Carbohydrates = 10,
                            CreatedOn = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 25,
                            Goal = 2,
                            ImageUrl = "https://www.lecremedelacrumb.com/wp-content/uploads/2019/04/sheet-pan-salmon-potatoes-asparagus-1-3.jpg",
                            Ingredients = "Salmon fillet, asparagus, olive oil, lemon",
                            IsDeleted = false,
                            Name = "Baked Salmon with Asparagus",
                            Preparation = "Preheat oven to 400°F (200°C). Place salmon and asparagus on a baking sheet. Drizzle with olive oil, lemon juice, salt, and pepper. Bake for 15-20 minutes until salmon is cooked through and asparagus is tender.",
                            Protein = 40
                        },
                        new
                        {
                            Id = new Guid("2995c236-5b5d-42f9-89b5-15576256ee66"),
                            Calories = 350,
                            Carbohydrates = 30,
                            CreatedOn = new DateTime(2024, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fats = 15,
                            Goal = 0,
                            ImageUrl = "https://thebeanbites.com/wp-content/uploads/2020/03/Instant-Pot-Stuffed-Peppers-10-720x540.jpg",
                            Ingredients = "Bell peppers, ground turkey, quinoa, cheese",
                            IsDeleted = false,
                            Name = "Stuffed Bell Peppers",
                            Preparation = "Preheat oven to 375°F (190°C). Cut the tops off bell peppers and remove seeds. In a bowl, mix cooked quinoa, ground turkey, and cheese. Stuff the mixture into the peppers. Place in a baking dish, cover with foil, and bake for 30 minutes. Uncover and bake for an additional 10 minutes.",
                            Protein = 25
                        });
                });

            modelBuilder.Entity("FitnessApp.Data.Models.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("FitnessApp.Data.Models.WorkoutExercise", b =>
                {
                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WorkoutId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("WorkoutsExercises");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Data.Models.Diet", b =>
                {
                    b.HasOne("FitnessApp.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Data.Models.DietRecipe", b =>
                {
                    b.HasOne("FitnessApp.Data.Models.Diet", "Diet")
                        .WithMany("DietsRecipes")
                        .HasForeignKey("DietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessApp.Data.Models.Recipe", "Recipe")
                        .WithMany("DietsRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diet");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("FitnessApp.Data.Models.Progress", b =>
                {
                    b.HasOne("FitnessApp.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Data.Models.Recipe", b =>
                {
                    b.HasOne("FitnessApp.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Data.Models.Workout", b =>
                {
                    b.HasOne("FitnessApp.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Data.Models.WorkoutExercise", b =>
                {
                    b.HasOne("FitnessApp.Data.Models.Exercise", "Exercise")
                        .WithMany("WorkoutsExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessApp.Data.Models.Workout", "Workout")
                        .WithMany("WorkoutsExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FitnessApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FitnessApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FitnessApp.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitnessApp.Data.Models.Diet", b =>
                {
                    b.Navigation("DietsRecipes");
                });

            modelBuilder.Entity("FitnessApp.Data.Models.Exercise", b =>
                {
                    b.Navigation("WorkoutsExercises");
                });

            modelBuilder.Entity("FitnessApp.Data.Models.Recipe", b =>
                {
                    b.Navigation("DietsRecipes");
                });

            modelBuilder.Entity("FitnessApp.Data.Models.Workout", b =>
                {
                    b.Navigation("WorkoutsExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
